### ISSUE TITLE
lithium incompatible

### ISSUE THREAD

**Issue by KITE2459** [cao-awa/Sepals#2]
![image](https://github.com/user-attachments/assets/53efc8f3-0345-4c8c-baf1-d19756b03a97)

lithium 0.13.1
seqals 1.0.3

**Comment by cao-awa** [comment]
Add this line:
```properties
mixin.entity.collisions.unpushable_cramming=false
```
to Lithium config or wait for me a few days to fix this

**Comment by cao-awa** [comment]
Fixed in version '1.0.4'.
