### ISSUE TITLE
C2ME incompatibility

### ISSUE THREAD

**Issue by chickenforday** [cao-awa/Sepals#3]
On Fabric 1.21.1-0.16.9
c2me-fabric-mc1.21.1-0.3.0+alpha.0.295
sepals-1.0.4

Results in not letting me join my world (I think the world doesn't load?)
Before I updated both mods, they were working fine 

https://mclo.gs/X80BoBJ

**Comment by MVukanichh** [comment]
Can confirm. If C2ME and Sepals are present on the server, the console is filled with errors while generating the world, resulting in the world never being made, with errors related to Sepals showing.

**Comment by cao-awa** [comment]
Fixed this bug in 1.0.5, please use in a new world.
