### ISSUE TITLE
Moonrise Incompatibility

### ISSUE THREAD

**Issue by EveningPrim** [cao-awa/Sepals#4]
Fabric 1.21.1-0.16.9
Latest Moonrise build (and previous builds)
sepals-1.0.5

Sepal works with Moonrise in an integrated server but joining dedicated results in a server crash

https://mclo.gs/B22YwVM
https://mclo.gs/2DObIEF

**Comment by cao-awa** [comment]
Fixed in '1.0.6', if your sepals config file has enabled 'forceEnableSepalsPoi', please set it to false.
