### ISSUE TITLE
[Enhancement] I know you’re busy but is a NeoForge port possible?

### ISSUE THREAD

**Issue by Cixon** [cao-awa/Sepals#6]
This mod has crazy potential and I’d love to also include it in my NeoForge modpack too so I’m curious if there’s a NeoForge version in development?

That is all, sorry for using your issue page as a suggestion pool. Have a great day!

**Comment by cao-awa** [comment]
I am not so busy yet, but maybe cannot port sepals to NeoForge quickly because i didn't have any forge-like mod development experiences. Icould try it but i don't know when.

And, thank you for your recognition!

**Comment by Cixon** [comment]
thank you for response. i hope NeoForge is possible! have a great day!

**Comment by cao-awa** [comment]
It available in Sepals '1.0.10' now, but no any compatible and bugs tested, only make sure it can work on NeoForge.
