### ISSUE TITLE
[Bug]: crash with c2me

### ISSUE THREAD

**Issue by iguanacucumber** [cao-awa/Sepals#7]
## Describe the bug
crash when c2me and sepals 1.0.7 are installed

## Reproduce
Run a server with c2me and sepals 1.0.7

## Expected behavior
Not to crash

## Environment
1. Your Java version: Grallvm 21 ( tested with others JVMs, and it doesnt matter )
2. Your Sepals version: 1.0.7
4. Your other mods: c2me
5. Your Minecraft version: 1.21.0

## latest.log
https://mclo.gs/YFqbCsg

**Comment by cao-awa** [comment]
sorry for second environment version, i am copy form the issue template from  my another project. that is your sepals version.

**Comment by cao-awa** [comment]
Alright, it's cause by kotlin. I will refactor all kotlin codes with Java to solve this.

**Comment by cao-awa** [comment]
Install the 'fabric-language-kotlin' mod to temporary solve this bug.

**Comment by cao-awa** [comment]
Done in '1.0.8'.
