### ISSUE TITLE
[Bug] 与async不兼容

### ISSUE THREAD

**Issue by baishu-rgb** [cao-awa/Sepals#9]
## Describe the bug
当async与sepals一起安装是会提示不兼容，然后无法启动服务器
async模组地址https://github.com/AxalotLDev/Async

## Reproduce
async与sepals一起安装在fabric 1.21.1服务器

## Expected behavior
async与sepals可以兼容

## Environment
java 23 
sepals 1.0.8
其它模组除了了这两个只有 fabric api

## latest.log
https://mclo.gs/qVEAK47

说实话，我觉得这个mod但从测试效果来看是极好的，而async也对实体进行了优化，不过它是尽可能调用多个线程运算这些实体，所以我觉得这两个激进的模组想要兼容应该不容易，但还是提了这个issus，请谅解

**Comment by cao-awa** [comment]
I am sorry for nothing can be done, because the mod 'Async' has explicitly declared in fabric.mod.json, it breaks game when you have installed any version of 'Sepals' or 'Monrise'. 
This is not a bug, maybe won't be fix never.

**Comment by cao-awa** [comment]
I have tested now, async is compatible with Sepals version '1.0.10', and not any no-vanilla behaviors found yet. Please try this version and attention to potential problems.

**Comment by baishu-rgb** [comment]
> I have tested now, async is compatible with Sepals version '1.0.10', and not any no-vanilla behaviors found yet (for entities). Please try this version and attention to potential problems.

thanks

**Comment by cao-awa** [comment]
Now Sepals version 1.0.11 is available, that done the compatible change to Async explicitly.
